name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
