name: Metrics
on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- Add this line

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year 

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.plugin.isocalendar.svg
          git commit -m "Update metrics [skip ci]" || echo "No changes to commit"
          git push
